export const SITE_NAME = 'Готель'
export const SITE_TAGLINE = 'Преміальний Лісовий Курорт'

export const NAV_LINKS = [
  { key: 'home', href: '/' },
  { key: 'about', href: '/#about' },
  { key: 'rooms', href: '/rooms' },
  { key: 'gallery', href: '/#gallery' },
  { key: 'contacts', href: '/contact' },
]

export const NAV_LABELS = {
  ua: {
    home: 'Головна',
    about: 'Про нас',
    rooms: 'Номери',
    gallery: 'Галерея',
    contacts: 'Контакти',
  },
  en: {
    home: 'Home',
    about: 'About',
    rooms: 'Rooms',
    gallery: 'Gallery',
    contacts: 'Contact',
  },
}

export const AMENITIES = [
  { id: 'wifi', label: 'Wi-Fi', icon: 'Wifi' },
  { id: 'parking', label: 'Паркінг', icon: 'Car' },
  { id: 'pool', label: 'Басейн', icon: 'Waves' },
  { id: 'breakfast', label: 'Сніданок', icon: 'Coffee' },
  { id: 'spa', label: 'СПА', icon: 'Sparkles' },
  { id: 'gym', label: 'Тренажерний зал', icon: 'Dumbbell' },
  { id: 'restaurant', label: 'Ресторан', icon: 'UtensilsCrossed' },
  { id: 'fireplace', label: 'Камін', icon: 'Flame' },
  { id: 'balcony', label: 'Балкон', icon: 'Sun' },
  { id: 'bath', label: 'Джакузі', icon: 'Bath' },
  { id: 'pets', label: 'Можна з тваринами', icon: 'PawPrint' },
  { id: 'sauna', label: 'Сауна', icon: 'Thermometer' },
]

export const ROOMS = [
  {
    id: '1',
    slug: 'standard',
    name: 'Стандартний номер',
    shortDescription: 'Затишний номер з видом на ліс та всіма необхідними зручностями для комфортного відпочинку.',
    description: 'Стандартний номер «Готель» — ідеальне поєднання природної краси та сучасного комфорту. Великі вікна відкривають панорамний вид на карпатський ліс, наповнюючи простір зеленим сяйвом. Натуральні матеріали в інтер\'єрі — дерево, льон, камінь — створюють атмосферу органічної розкоші. Просторе ліжко з ортопедичним матрацом забезпечить глибокий відновлювальний сон.',
    price: 3200,
    originalPrice: null,
    currency: 'UAH',
    size: 28,
    maxGuests: 2,
    bedType: 'Двоспальне ліжко',
    floor: '2-4',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&q=80',
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=1200&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80',
      'https://images.unsplash.com/photo-1562438668-bcf0ca6578f0?w=1200&q=80',
    ],
    amenities: ['wifi', 'breakfast', 'parking', 'gym'],
    featured: false,
    rating: 4.7,
    reviewCount: 124,
    category: 'standard',
  },
  {
    id: '2',
    slug: 'forest-suite',
    name: 'Лісовий люкс',
    shortDescription: 'Просторий люкс з терасою, відкритою ванною та приголомшливим видом на ліс.',
    description: 'Лісовий люкс занурює вас у серце природи. Просторий інтер\'єр площею 52 м² поєднує скандинавський мінімалізм та карпатський характер. Французький балкон з панорамним заскленням дозволяє насолоджуватися лісом навіть вночі. Окрема вітальня з м\'яким диваном і бібліотекою, відкрита кам\'яна ванна, ексклюзивна косметика — все для повного відновлення.',
    price: 5800,
    originalPrice: null,
    currency: 'UAH',
    size: 52,
    maxGuests: 2,
    bedType: 'King-size ліжко',
    floor: '3-5',
    images: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=80',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200&q=80',
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1200&q=80',
      'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=1200&q=80',
    ],
    amenities: ['wifi', 'breakfast', 'spa', 'fireplace', 'balcony', 'bath', 'parking'],
    featured: true,
    rating: 4.9,
    reviewCount: 89,
    category: 'suite',
  },
  {
    id: '3',
    slug: 'lake-house',
    name: 'Котедж біля озера',
    shortDescription: 'Окремий котедж прямо на березі озера з власним причалом і сауною.',
    description: 'Котедж «Озерний» — найромантичніше місце курорту. Розташований безпосередньо на березі природного озера, він пропонує унікальний досвід єднання з водою та лісом. Власний причал для рибалки та прогулянок на каяках, фінська сауна з виходом до озера, відкрита тераса з барбекю — все це створює ідеальний простір для приватного відпочинку.',
    price: 9500,
    originalPrice: 11000,
    currency: 'UAH',
    size: 95,
    maxGuests: 4,
    bedType: '2 спальні (King + Twin)',
    floor: '1 поверх',
    images: [
      'https://images.unsplash.com/photo-1601918774946-25832a4be0d6?w=1200&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80',
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=80',
    ],
    amenities: ['wifi', 'breakfast', 'sauna', 'fireplace', 'balcony', 'pets', 'parking', 'restaurant'],
    featured: true,
    rating: 5.0,
    reviewCount: 67,
    category: 'cottage',
  },
  {
    id: '4',
    slug: 'family-suite',
    name: 'Сімейний люкс',
    shortDescription: 'Ідеальний вибір для сімей з дітьми — дві спальні, дитяча кімната та простора вітальня.',
    description: 'Сімейний люкс — простір, де кожен знайде своє місце. Дві повноцінні спальні з власними санвузлами, простора вітальня з кухонним куточком, окрема дитяча кімната з іграшками та безпечним дитячим ліжечком. Великий балкон стає спільним місцем для ранкового чаю та вечірніх оповідань.',
    price: 7200,
    originalPrice: null,
    currency: 'UAH',
    size: 78,
    maxGuests: 5,
    bedType: 'King + Twin + Дитяче',
    floor: '2-4',
    images: [
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=1200&q=80',
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200&q=80',
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=1200&q=80',
      'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&q=80',
    ],
    amenities: ['wifi', 'breakfast', 'parking', 'pool', 'gym', 'balcony'],
    featured: false,
    rating: 4.8,
    reviewCount: 103,
    category: 'suite',
  },
  {
    id: '5',
    slug: 'spa-penthouse',
    name: 'СПА-пентхаус',
    shortDescription: 'Найвища точка курорту з панорамним видом 360°, приватним СПА та джакузі на даху.',
    description: 'СПА-пентхаус — вершина розкоші в буквальному сенсі. Весь верхній поверх корпусу з панорамним заскленням, що відкриває вид на 360° — ліс, озеро, карпатські гори на горизонті. Приватний СПА-комплекс: джакузі, хамам, сауна, масажний стіл. Особистий консьєрж та шеф-кухар доступні цілодобово.',
    price: 18500,
    originalPrice: null,
    currency: 'UAH',
    size: 140,
    maxGuests: 2,
    bedType: 'Emperor-size ліжко',
    floor: 'Пентхаус',
    images: [
      'https://images.unsplash.com/photo-1631049552240-59c37f38802b?w=1200&q=80',
      'https://images.unsplash.com/photo-1540541338537-ad38fbfc9b7f?w=1200&q=80',
      'https://images.unsplash.com/photo-1561501900-3701fa6a0864?w=1200&q=80',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&q=80',
    ],
    amenities: ['wifi', 'breakfast', 'spa', 'bath', 'sauna', 'fireplace', 'balcony', 'parking', 'restaurant', 'gym'],
    featured: true,
    rating: 5.0,
    reviewCount: 42,
    category: 'penthouse',
  },
  {
    id: '6',
    slug: 'forest-studio',
    name: 'Студія «Ліс»',
    shortDescription: 'Компактна та стильна студія для тих, хто цінує мінімалізм та близькість до природи.',
    description: 'Студія «Ліс» — простір для тих, хто знає, що справжня розкіш — у простоті. Відкрите планування 35 м², де кожна деталь продумана до дрібниць. Великий лофт-стіл для роботи або творчості, кухонний куточок з кавомашиною від Illy, дизайнерська ванна кімната з дощовим душем.',
    price: 4100,
    originalPrice: null,
    currency: 'UAH',
    size: 35,
    maxGuests: 2,
    bedType: 'Queen-size ліжко',
    floor: '1-3',
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=1200&q=80',
      'https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=1200&q=80',
    ],
    amenities: ['wifi', 'breakfast', 'gym', 'parking'],
    featured: false,
    rating: 4.6,
    reviewCount: 156,
    category: 'studio',
  },
]

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Олена Коваленко',
    location: 'Київ',
    rating: 5,
    text: 'Неймовірне місце! Приїхали з чоловіком на 3 ночі в Лісовому люксі — це був найкращий відпочинок за останні роки. Природа, тиша, фантастична кухня. Вже плануємо повернутися з дітьми.',
    date: '2024-12',
    avatar: '/images/logo.svg',
  },
  {
    id: 2,
    name: 'Максим Петренко',
    location: 'Львів',
    rating: 5,
    text: 'Котедж біля озера — це щось неймовірне. Ранкова рибалка, вечірня сауна, зоряне небо над головою. Сервіс на рівні найкращих європейських готелів. Рекомендую всім, хто цінує справжній відпочинок.',
    date: '2024-11',
    avatar: '/images/logo.svg',
  },
  {
    id: 3,
    name: 'Наталія Бондаренко',
    location: 'Харків',
    rating: 5,
    text: 'СПА-пентхаус перевершив всі очікування. Вид на гори, приватне джакузі, неперевершений сервіс — все ідеально. Особлива подяка шеф-кухарю за дегустаційне меню з місцевих продуктів.',
    date: '2025-01',
    avatar: '/images/logo.svg',
  },
  {
    id: 4,
    name: 'Андрій Мельник',
    location: 'Дніпро',
    rating: 5,
    text: 'Ідеальне місце для сімейного відпочинку! Діти були в захваті від природи та активностей. Персонал дуже уважний та привітний. Обов\'язково повернемося наступного літа.',
    date: '2024-10',
    avatar: '/images/logo.svg',
  },
]

export const RESORT_FEATURES = [
  {
    icon: 'ShieldCheck',
    title: 'Преміальний сервіс 24/7',
    description: 'Персональний консьєрж, room service та підтримка гостей цілодобово для бездоганного відпочинку.',
  },
  {
    icon: 'Sparkles',
    title: 'Преміальний СПА-центр',
    description: 'Повний спектр оздоровчих процедур: масажі, обгортання, ванни з трав\'яними відварами.',
  },
  {
    icon: 'ChefHat',
    title: 'Авторська кухня',
    description: 'Ресторан використовує виключно локальні продукти від місцевих фермерів та власний сад.',
  },
  {
    icon: 'Waves',
    title: 'Природне озеро',
    description: 'Плавання, рибалка, каяки та SUP-серфінг на кристально чистому гірському озері.',
  },
]

export const ROOM_CATEGORIES = [
  { id: 'all', key: 'all' },
  { id: 'standard', key: 'standard' },
  { id: 'studio', key: 'studio' },
  { id: 'suite', key: 'suite' },
  { id: 'cottage', key: 'cottage' },
  { id: 'penthouse', key: 'penthouse' },
]

export const SORT_OPTIONS = [
  { id: 'popular', key: 'popular' },
  { id: 'price_asc', key: 'price_asc' },
  { id: 'price_desc', key: 'price_desc' },
  { id: 'rating', key: 'rating' },
]

export const ANIMATION_DURATION = {
  fast: 0.2,
  normal: 0.4,
  slow: 0.6,
}

export const STAGGER_DELAY = 0.08
